### PR TITLE
feature: star history across org

### PR DESCRIPTION
**Pull request by ykdojo**
- Show a star chart for a whole organization (#11). For now, it only works with organizations with <= 100 repos. I'll make an issue to adjust this problem.
- Refactor the function that POSTs to GitHub API v4
- Show totalStarCount when loading a star history

### CODE REVIEW

**Comment by joshenlim** [comment]
Retrieving the star history for the organization is similar to how we're doing it for each repository right? So technically once a user enters the organization page, we're actually gonna start fetching the star histories for all of the repositories? (i.e once the star history of the organization loads finish, the star histories of each repo will already be cached in SB)

**Comment by joshenlim** [comment]
Also I'm noticing a `stargazers` of null error for certain organizations like vercel or django

**Comment by joshenlim** [comment]
Okay no worries - i found out a fix for the bug above ^ under [org].index.js, we have 2 separate async useEffects that are trying to retrieve the organization profile and organization repositories separately, leading to a sort of race condition issue - There were occasions whereby the organization API call loaded first but not the repository, hence the starAggregator tried to retrieve star histories for repositories under the wrong organization (or vice versa)

I've combined the 2 useEffects and leveraged on the `loaded` state to call the starAggregator

**Comment by joshenlim** [comment]
Okay this looks really good 👍 A couple of small bugs i noticed but i'll open a separate issue, will merge this in first :)

**Comment by ykdojo** [comment]
Thanks @joshenlim!

> Retrieving the star history for the organization is similar to how we're doing it for each repository right? So technically once a user enters the organization page, we're actually gonna start fetching the star histories for all of the repositories? (i.e once the star history of the organization loads finish, the star histories of each repo will already be cached in SB)

Yes that's correct.

**Pull request merged**
