### PR TITLE
Feature/embeddable charts

### PR DESCRIPTION
**Pull request by joshenlim**
## What kind of change does this PR introduce?

Fixes https://github.com/supabase/repository.surf/issues/1

Allows iframe embedding of our charts, demo: https://codepen.io/joshenlim/pen/oNzpeLZ?editors=1000

Done via this url: http://localhost:3000/supabase/supabase?embed=true&type=[chartType]

Where chart type is currently either issues or stars

### CODE REVIEW

**Comment by kiwicopple** [comment]
I couldnt see this one working from the code pen - 

image

Perhaps it's not deployed yet though?

**Comment by joshenlim** [comment]
Oh that's weird hmm, could you try it in incog? This is how it's looking like for me

image

**Comment by kiwicopple** [comment]
Tried again in incognito (Firefox) with adblock turned off - same result.

**Comment by joshenlim** [comment]
Gotcha! I'll reopen the issue again - will investigate

**Comment by kiwicopple** [comment]
Perhaps also just embed the chart, but not the title & text etc? People might want to add their own text/language

**Comment by joshenlim** [comment]
Ahhh okay, so there was something going on with using iframes in codepen on Firefox specifically, here's a demo on codesandbox instead: https://codesandbox.io/s/supabase-embed-demo-iyzyk

Will keep the issue opened - still want to do some refactors as well

**Pull request merged**
